[package]
description = "Models of the Rust core library"
name = "test-foo-bar-core-models"
readme = "readme.md"
version = "0.0.6"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
hax-lib.workspace = true
pastey = "0.2.0"
rand = "0.10"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(hax)'] }
