[package]
authors.workspace = true
description = "pqclean wrapper for libcrux tests and benchmarks."
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "test-foo-bar-pqclean"
publish = false
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]

[build-dependencies]
bindgen = "0.72"
cc = { version = "1.1", features = ["parallel"] }
fs_extra = "1.2"
