[package]
description = "Libcrux KEM implementation"
name = "test-foo-bar-kem"
readme = "README.md"
version = "0.0.8"

authors.workspace = true
edition.workspace = true
exclude = ["/tests"]
homepage.workspace = true
license.workspace = true
repository.workspace = true

[lib]
path = "src/kem.rs"

[dependencies]
test-foo-bar-curve25519.workspace = true
test-foo-bar-ecdh.workspace = true
test-foo-bar-ml-kem = { workspace = true, features = ["default-no-std"] }
test-foo-bar-p256.workspace = true
test-foo-bar-sha3.workspace = true
test-foo-bar-traits.workspace = true

rand = { version = "0.10", default-features = false }
tls_codec = { version = "0.4.2", features = ["derive"], optional = true }

[features]
default = ["std"]
pre-verification = []
std = ["rand/std", "test-foo-bar-ecdh/std", "test-foo-bar-ml-kem/std"]
tests = []                                                             # Expose functions for testing.
# Encoding and decoding with TLSCodec
codec = [
    "dep:tls_codec",
    "test-foo-bar-ecdh/codec",
    "test-foo-bar-ml-kem/codec",
]

[dev-dependencies]
hex = { version = "0.4.3", features = ["serde"] }
rand = { version = "0.10", features = ["sys_rng"] }
rand_core = { version = "0.10" }
test-foo-bar-kem = { path = "./", features = ["tests"] }
test-foo-bar-traits = { workspace = true, features = ["generic-tests"] }
