[package]
description = "Formally verified ChaCha20-Poly1305 AEAD library"
name = "test-foo-bar-chacha20poly1305"
readme = "Readme.md"
version = "0.0.9"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
test-foo-bar-hacl-rs.workspace = true
test-foo-bar-macros = { version = "=0.0.4", path = "../../utils/macros" }
test-foo-bar-poly1305 = { version = "=0.0.7", path = "../poly1305/", features = [
    "expose-hacl",
] }
test-foo-bar-secrets.workspace = true
test-foo-bar-traits.workspace = true

[dev-dependencies]
hex = { version = "0.4.3", features = ["serde"] }
rand = { version = "0.10", features = ["sys_rng"] }
rand_core = { version = "0.10" }
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"

[features]
check-secret-independence = ["test-foo-bar-secrets/check-secret-independence"]
