[package]
description = "Libcrux HMAC implementation"
name = "test-foo-bar-hmac"
readme = "Readme.md"
version = "0.0.7"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[lib]
path = "src/hmac.rs"

[features]
expose-hacl = []

[dependencies]
test-foo-bar-hacl-rs.workspace = true
test-foo-bar-macros = { version = "=0.0.3", path = "../../utils/macros" }
test-foo-bar-sha2 = { workspace = true, features = ["expose-hacl"] }
