[package]
description = "Formally verified SHA2 hash library"
name = "test-foo-bar-sha2"
readme = "Readme.md"
version = "0.0.7"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[features]
expose-hacl = []

[dependencies]
test-foo-bar-hacl-rs.workspace = true
test-foo-bar-macros = { version = "=0.0.3", path = "../../utils/macros" }
test-foo-bar-traits.workspace = true

[dev-dependencies]
hex = "0.4.3"
test-foo-bar-kats = { workspace = true, features = ["sha2"] }
test-foo-bar-traits = { workspace = true, features = ["generic-tests"] }
