[package]
authors.workspace = true
description = "Rust bindings for libjade, a formally verified cryptographic library written in jasmin."
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "libjade-sys"
publish = false
readme = "Readme.md"
repository.workspace = true
version.workspace = true

[dependencies]

[build-dependencies]
cc = { version = "1.1", features = ["parallel"] }
test-foo-bar-platform = { version = "=0.0.3", path = "../platform" }

[target.'cfg(not(windows))'.build-dependencies]
bindgen = { version = "0.72", optional = true }

[dev-dependencies]
pretty_env_logger = "0.5"

[features]
bindings = ["bindgen"]
