[package]
authors.workspace = true
description = "Libcrux helper to read NIST CAVP test vectors."
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "test-foo-bar-cavp"
readme = "Readme.md"
repository.workspace = true
version.workspace = true

[dependencies]
hex = "0.4.3"
log = "0.4.22"

[dev-dependencies]
pretty_env_logger = "0.5.0"
