[package]
description = "Formally verified curve25519 ECDH library"
name = "test-foo-bar-curve25519"
readme = "Readme.md"
version = "0.0.8"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
test-foo-bar-hacl-rs.workspace = true
test-foo-bar-macros = { version = "=0.0.4", path = "../../utils/macros" }
test-foo-bar-secrets.workspace = true
test-foo-bar-traits.workspace = true

[features]
# Checking secret independence
check-secret-independence = [
    "test-foo-bar-secrets/check-secret-independence",
    "test-foo-bar-traits/check-secret-independence",
]

[dev-dependencies]
test-foo-bar-traits = { workspace = true, features = ["generic-tests"] }
