[package]
description = "Formally verified ed25519 signature library"
name = "test-foo-bar-ed25519"
readme = "Readme.md"
version = "0.0.8"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rand_core = { version = "0.10", optional = true }
test-foo-bar-hacl-rs.workspace = true
test-foo-bar-macros = { version = "=0.0.3", path = "../../utils/macros" }
test-foo-bar-sha2 = { workspace = true, features = ["expose-hacl"] }
tls_codec = { version = "0.4.2", features = ["derive"], optional = true }

[dev-dependencies]
hex = "0.4.3"
rand = { version = "0.10" }
wycheproof = "0.6.0"

[features]
codec = ["tls_codec/std"]
rand = ["dep:rand_core"]
