[package]
edition = "2021"
name = "test-foo-bar-ml-kem-fuzz"
publish = false
version = "0.0.0"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.test-foo-bar-ml-kem]
path = ".."

[[bin]]
bench = false
doc = false
name = "keygen"
path = "fuzz_targets/keygen.rs"
test = false

[[bin]]
bench = false
doc = false
name = "encaps"
path = "fuzz_targets/encaps.rs"
test = false

[[bin]]
bench = false
doc = false
name = "decaps"
path = "fuzz_targets/decaps.rs"
test = false
