[package]
description = "Formally verified AEAD library"
name = "test-foo-bar-aead"
readme = "Readme.md"
version = "0.0.8"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
test-foo-bar-aesgcm = { workspace = true, optional = true }
test-foo-bar-chacha20poly1305 = { workspace = true, optional = true }
test-foo-bar-secrets.workspace = true
test-foo-bar-traits = { workspace = true, optional = true }

[features]
aesgcm128 = ["dep:test-foo-bar-aesgcm", "dep:test-foo-bar-traits"]
aesgcm256 = ["dep:test-foo-bar-aesgcm", "dep:test-foo-bar-traits"]
chacha20poly1305 = [
    "dep:test-foo-bar-chacha20poly1305",
    "dep:test-foo-bar-traits",
]
check-secret-independence = [
    "test-foo-bar-secrets/check-secret-independence",
    "test-foo-bar-traits/check-secret-independence",
]
default = ["aesgcm128", "aesgcm256", "chacha20poly1305", "xchacha20poly1305"]
xchacha20poly1305 = [
    "dep:test-foo-bar-chacha20poly1305",
    "dep:test-foo-bar-traits",
]
