[package]
description = "Formally verified Poly1305 MAC library"
name = "test-foo-bar-poly1305"
readme = "Readme.md"
version = "0.0.6"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[features]
expose-hacl = []

[dependencies]
test-foo-bar-hacl-rs.workspace = true
test-foo-bar-macros = { version = "=0.0.3", path = "../../utils/macros" }

[dev-dependencies]
test-foo-bar-kats = { workspace = true, features = ["poly1305"] }
test-foo-bar-poly1305 = { path = ".", features = ["expose-hacl"] }
