[package]
description = "Formally verified blake2 hash library"
name = "test-foo-bar-blake2"
readme = "Readme.md"
version = "0.0.8"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = ["std"]
std = []

[dependencies]
test-foo-bar-hacl-rs.workspace = true
test-foo-bar-macros.workspace = true
test-foo-bar-traits.workspace = true

[dev-dependencies]
criterion = "0.8"
rand = "0.10"
test-foo-bar-traits = { workspace = true, features = ["generic-tests"] }

[[bench]]
harness = false
name = "blake2"
