[package]
description = "Formally verified P-256 implementation"
name = "test-foo-bar-p256"
readme = "Readme.md"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
version = "0.0.8"

[dependencies]
test-foo-bar-hacl-rs.workspace = true
test-foo-bar-macros = { version = "=0.0.4", path = "../../utils/macros" }
test-foo-bar-secrets.workspace = true
test-foo-bar-sha2 = { workspace = true, features = ["expose-hacl"] }
test-foo-bar-traits.workspace = true

[features]
expose-hacl = []

# Checking secret independence
check-secret-independence = [
    "test-foo-bar-secrets/check-secret-independence",
    "test-foo-bar-traits/check-secret-independence",
]


[dev-dependencies]
test-foo-bar-traits = { workspace = true, features = ["generic-tests"] }
