[package]
description = "Libcrux ML-DSA implementation"
name = "test-foo-bar-ml-dsa"
readme = "README.md"
version = "0.0.9"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

exclude = [
    "*.sh",
    "*.yaml",
    "/cg",
    "/proofs",
    "boring.sh",
    "tests/kats",
    "tests/nistkats.rs",
]

[lib]
bench = false # so libtest doesn't eat the arguments to criterion

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hax-lib.workspace = true
test-foo-bar-intrinsics.workspace = true
test-foo-bar-macros.workspace = true
test-foo-bar-platform.workspace = true
test-foo-bar-sha3.workspace = true
tls_codec = { version = "0.4.2", features = [
    "derive",
], default-features = false, optional = true }

[dev-dependencies]
criterion = "0.8"
hex = { version = "0.4.3", features = ["serde"] }
rand = { version = "0.10" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
test-foo-bar-kats = { workspace = true, features = ["mldsa"] }


# This doesn't build on intel macos.
[target.'cfg(not(all(target_os = "macos", target_arch = "x86_64")))'.dev-dependencies]
pqcrypto-mldsa = { version = "0.1.0" } #, default-features = false

[target.'cfg(hax)'.dependencies]
test-foo-bar-core-models = { path = "../crates/utils/core-models", version = "0.0.7" }

[features]
acvp = []                                                                  # expose internal API for ACVP testing
default = ["mldsa44", "mldsa65", "mldsa87", "std"]
simd128 = ["test-foo-bar-intrinsics/simd128", "test-foo-bar-sha3/simd128"]
simd256 = ["test-foo-bar-intrinsics/simd256", "test-foo-bar-sha3/simd256"]
test-utils = []                                                            # exposing internal functions for testing

# Features for the different key sizes of ML-DSA
mldsa44 = []
mldsa65 = []
mldsa87 = []

# std support
std = []

# Serialization & Deserialization using tls_codec
codec = ["dep:tls_codec"]

[[bench]]
harness = false
name = "manual44"

[[bench]]
harness = false
name = "manual65"

[[bench]]
harness = false
name = "manual87"

[[bench]]
harness = false
name = "ml-dsa"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(hax)'] }
