[package]
authors.workspace = true
description = "Platform detection crate for libcrux."
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "test-foo-bar-platform"
readme.workspace = true
repository.workspace = true

version = "0.0.4"

[dependencies]
libc = "0.2.153"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(eurydice)', 'cfg(hax)'] }
