[package]
description = "Formally verified Rust code extracted from HACL* - helper library"
name = "test-foo-bar-hacl-rs"
version = "0.0.5"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
test-foo-bar-macros.workspace = true

[lib]
