[package]
edition = "2021"
name = "test-foo-bar-psq-fuzz"
publish = false
version = "0.0.0"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
rand = "0.10"
test-foo-bar-ml-kem = { workspace = true, default-features = true, features = [
    "rand",
] }

[dependencies.test-foo-bar-psq]
path = ".."

[[bin]]
bench = false
doc = false
harness = false
name = "responder_read_message"
path = "fuzz_targets/responder_read_message.rs"
test = false

[[bin]]
bench = false
doc = false
harness = false
name = "query_initiator_read_response"
path = "fuzz_targets/query_initiator_read_response.rs"
test = false

[[bin]]
bench = false
doc = false
harness = false
name = "registration_initiator_read_response"
path = "fuzz_targets/registration_initiator_read_response.rs"
test = false

[[bin]]
bench = false
doc = false
harness = false
name = "session_deserialize"
path = "fuzz_targets/session_deserialize.rs"
test = false

[[bin]]
bench = false
doc = false
harness = false
name = "transport_read_message"
path = "fuzz_targets/transport_read_message.rs"
test = false
