[package]
description = "Traits for cryptographic algorithms"
name = "test-foo-bar-traits"
version = "0.0.7"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true

[features]
# core::error::Error is still pretty recent, so we only implement it for our errors behind a feature
error-in-core = []
# enables checking of secret-independence
check-secret-independence = ["test-foo-bar-secrets/check-secret-independence"]
# expose tests that are generic over the traits
generic-tests = []
# whether or not the alloc crate is used
alloc = []

[dependencies]
rand = { version = "0.10", default-features = false }
test-foo-bar-secrets.workspace = true
