[package]
description = "Libcrux Pre-Shared post-Quantum key establishement protocol"
name = "test-foo-bar-psq"
readme = "README.md"
version = "0.0.9"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish = true
repository.workspace = true

[lib]
bench = false # so libtest doesn't eat the arguments to criterion

[dependencies]
classic-mceliece-rust = { version = "3.1.0", features = [
    "mceliece460896f",
    "zeroize",
], optional = true }
rand = { version = "0.10" }
rand_old = { version = "0.8", package = "rand", optional = true }
test-foo-bar-aesgcm.workspace = true
test-foo-bar-chacha20poly1305.workspace = true
test-foo-bar-ecdh = { workspace = true, default-features = true }
test-foo-bar-ed25519 = { workspace = true, features = ["codec", "rand"] }
test-foo-bar-hkdf.workspace = true
test-foo-bar-hmac.workspace = true
test-foo-bar-kem = { workspace = true, features = ["codec"] }
test-foo-bar-ml-dsa = { workspace = true, features = ["codec"] }
test-foo-bar-ml-kem = { workspace = true, default-features = true, features = [
    "codec",
    "rand",
] }
test-foo-bar-sha2.workspace = true
test-foo-bar-traits.workspace = true
tls_codec = { version = "0.4.2", features = ["derive"] }

[dev-dependencies]
clap = { version = "4.5.30", features = ["derive"] }
criterion = "0.8"
log = "0.4.26"
pretty_env_logger = "0.5.0"
rand_core = { version = "0.10" }

[features]
classic-mceliece = ["dep:classic-mceliece-rust", "rand_old"]
v1 = []

# Allows external control over the AEAD nonces of transport channels.
# ⚠️ CAUTION! Enabling this makes it the responsibility of the application to avoid nonce re-use.
nonce-control = []

[[bench]]
harness = false
name = "psq_v2"
